name: Yarn Audit Telemetry

on:
  schedule:
    # every 12 hours
    - cron: "0 */6 * * *"

  # This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

jobs:
  post-to-splunk-hec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g yarn
      - run: |
          # ignore exitcode: https://classic.yarnpkg.com/en/docs/cli/audit
          yarn audit --json >> report.json || true
          # auditAdvisory
          curl -k "${SPLUNK_URI}/services/collector" \
               -H "Authorization: Splunk ${SPLUNK_HEC_TOKEN}" \
               -d "{\"event\": `sed '1!d' report.json`, \"sourcetype\": \"${SPLUNK_SOURCETYPE}\", \"source\": \"${SPLUNK_SOURCE}\"}"
          # auditSummary
          curl -k "${SPLUNK_URI}/services/collector" \
               -H "Authorization: Splunk ${SPLUNK_HEC_TOKEN}" \
               -d "{\"event\": `sed '2!d' report.json`, \"sourcetype\": \"${SPLUNK_SOURCETYPE}\", \"source\": \"${SPLUNK_SOURCE}\"}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SPLUNK_HEC_TOKEN: ${{ secrets.SPLUNK_HEC_TOKEN }}
          SPLUNK_URI: ${{ secrets.SPLUNK_URI }}
          SPLUNK_SOURCETYPE: yarn:audit
          SPLUNK_SOURCE: react-app-with-vuln-telemetry