name: NPM Audit Telemetry

on:
  schedule:
    # every 12 hours
    - cron: "0 */6 * * *"

  # This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

jobs:
  post-to-splunk-hec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          curl -k "${SPLUNK_URI}/services/collector" \
               -H "Authorization: ${SPLUNK_HEC_TOKEN}" \
               -d "{\"event\": `npm audit --json`, \"sourcetype\": \"${SPLUNK_SOURCETYPE}\", \"source\": \"${SPLUNK_SOURCE}\"}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SPLUNK_HEC_TOKEN: ${{ secrets.SPLUNK_HEC_TOKEN }}
          SPLUNK_URI: ${{ secrets.SPLUNK_URI }}
          SPLUNK_SOURCETYPE: npm:audit
          SPLUNK_SOURCE: react-app-with-vuln-telemetry